### ISSUE TITLE
Verify that version detection works with Java 10 in all situations

### ISSUE THREAD

**Issue by ctrueden** [imagej/ij1-patcher#45]
Attempting to launch Fiji with a snapshot of Java 10 dies with:
```
java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.imagej.patcher.LegacyEnvironment.isImageJ1Initialized(LegacyEnvironment.java:553)
	... 22 more
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3107)
	at java.base/java.lang.String.substring(String.java:1873)
	at ij.IJ.<clinit>(IJ.java:76)
	... 27 more
```
Launching with `$J10/bin/java -jar ij-1.51u.jar` works, however, as does:
```
$J10/bin/java -cp '*':bio-formats/'*':../plugins/'*' net.imagej.Main
```

**Comment by ctrueden** [comment]
Cannot reproduce today. Closing for now.
