### ISSUE TITLE
Update the patcher for ImageJ 1.53g - 1.53p

### ISSUE THREAD

**Issue by imagejan** [imagej/ij1-patcher#50]
See [this forum post](https://forum.image.sc/t/fiji-fails-to-launch-after-upgade-to-imagej-daily-build/47125?u=imagejan).

**Comment by rasband** [comment]
Fiji failed to launch because the ImageJ daily builds (1.53h17, 1.53h19 and 1.53h20) were built for Java 8.

This is the exception:

> Error while executing the main() method of class 'net.imagej.Main':
> java.lang.NullPointerException
> 	at net.imagej.legacy.ui.LegacyUI.ij1Helper(LegacyUI.java:119)
> 	at net.imagej.legacy.ui.LegacyUI.show(LegacyUI.java:130)
> 	at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:158)
> 	at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:143)
> 	at org.scijava.AbstractGateway.launch(AbstractGateway.java:110)
> 	at net.imagej.Main.main(Main.java:55)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:291)
> 	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:198)
> 	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:89)
> 
>

**Comment by mkitti** [comment]
Have any of you tried `.\ImageJ-win64.exe -Xverify:none --`

**Comment by mkitti** [comment]
If I just do `.\ImageJ-win64.exe --debug`, it eventually fails with this:

```
Error while executing the main() method of class 'net.imagej.Main':
java.lang.NullPointerException
        at net.imagej.legacy.ui.LegacyUI.ij1Helper(LegacyUI.java:119)
        at net.imagej.legacy.ui.LegacyUI.show(LegacyUI.java:130)
        at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:158)
        at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:143)
        at org.scijava.AbstractGateway.launch(AbstractGateway.java:110)
        at net.imagej.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:291)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:198)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:89)
[ERROR] Exception during event handling:
        [Event] org.scijava.service.event.ServicesLoadedEvent
        context = org.scijava.Context@c7a975a
        consumed = false
        [Subscriber] sc.fiji.compat.DefaultFijiService [priority = 0.0]
        [Method] protected void sc.fiji.compat.DefaultFijiService.onEvent(org.scijava.service.event.ServicesLoadedEvent)
java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    ij/IJ.getClassLoader()Ljava/lang/ClassLoader; @176: nop
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: b20b b201 a600 24b8 005b b60b b5b3 0bb2
    0x0000010: b20b b204 b80b b94b 2a01 a500 0eb8 005b
    0x0000020: 2ab6 0b72 2ab3 0bb2 b20b b2b0 0000 00a7
    0x0000030: fffd 0000 0000 00a7 fffb 0000 0000 0000
    0x0000040: 0000 0000 0000 0000 0000 0000 a7ff ee00
    0x0000050: 0000 0000 0000 a7ff f9a7 0000 0000 a7ff
    0x0000060: fe00 0000 00a7 fffc 0000 0000 0000 00a7
    0x0000070: fff9 0000 0000 0000 0000 0000 0000 0000
    0x0000080: 0000 0000 a7ff ee00 0000 0000 0000 0000
    0x0000090: 0000 0000 0000 0000 0000 0000 0000 0000
    0x00000a0: 0000 0000 0000 0000 0000 0000 00a7 ffda
    0x00000b0: 00bf 00a7 ffff 0000 0000 a7ff fc00 0000
    0x00000c0: a7ff fd00 0000 0000 0000 0000 0000 00a7
    0x00000d0: fff4 0000 0000 0000 0000 a7ff f800 a7ff
    0x00000e0: ff
  Stackmap Table:
    same_frame(@40)
    same_frame(@44)
    same_frame(@50)
    same_frame(@58)
    same_frame(@79)
    same_frame(@89)
    same_frame(@92)
    same_frame(@97)
    same_frame(@104)
    same_frame(@114)
    same_frame(@135)
    same_frame(@178)
    same_frame(@182)
    same_frame(@189)
    same_frame(@195)
    same_frame(@210)
    same_frame(@221)

        at sc.fiji.compat.DefaultFijiService.actuallyInitialize(DefaultFijiService.java:54)
        at sc.fiji.compat.DefaultFijiService.onEvent(DefaultFijiService.java:77)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.scijava.event.DefaultEventService$ProxySubscriber.onEvent(DefaultEventService.java:298)
        at org.scijava.event.DefaultEventService$ProxySubscriber.onEvent(DefaultEventService.java:272)
        at org.bushe.swing.event.ThreadSafeEventService.publish(ThreadSafeEventService.java:971)
        at org.scijava.event.DefaultEventBus.access$201(DefaultEventBus.java:54)
        at org.scijava.event.DefaultEventBus$2.run(DefaultEventBus.java:214)
        at org.scijava.thread.DefaultThreadService.lambda$wrap$1(DefaultThreadService.java:211)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by mkitti** [comment]
If I run `.\ImageJ-win64.exe -Xverify:none -- --debug`, there are a few `java.lang.IllegalArgumentException` but FIJI does start and the GUI pops up.

```
[DEBUG] Creating service: net.imagej.legacy.LegacyService
java.lang.IllegalArgumentException: Method void createMacro() in ij.plugin.frame.Recorder does not return on null
        at net.imagej.patcher.CodeHacker.dontReturnOnNull(CodeHacker.java:497)
        at net.imagej.patcher.LegacyExtensions.addEditorExtensionPoints(LegacyExtensions.java:320)
        at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:287)
        at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:306)
        at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:107)
        at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:100)
        at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:494)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:395)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:374)
        at net.imagej.legacy.LegacyService.<clinit>(LegacyService.java:141)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:300)
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:267)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:229)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:192)
        at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:164)
        at org.scijava.Context.<init>(Context.java:278)
        at org.scijava.Context.<init>(Context.java:234)
        at org.scijava.Context.<init>(Context.java:174)
        at org.scijava.Context.<init>(Context.java:160)
        at net.imagej.ImageJ.<init>(ImageJ.java:77)
        at net.imagej.Main.main(Main.java:54)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:291)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:198)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:89)
java.lang.IllegalArgumentException: Cannot handle replace call to runPlugIn in ij.plugin.frame.Recorder's void createMacro()
        at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:723)
        at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:648)
        at net.imagej.patcher.LegacyExtensions.addEditorExtensionPoints(LegacyExtensions.java:321)
        at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:287)
        at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:306)
        at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:107)
        at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:100)
        at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:494)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:395)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:374)
        at net.imagej.legacy.LegacyService.<clinit>(LegacyService.java:141)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:300)
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:267)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:229)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:192)
        at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:164)
        at org.scijava.Context.<init>(Context.java:278)
        at org.scijava.Context.<init>(Context.java:234)
        at org.scijava.Context.<init>(Context.java:174)
        at org.scijava.Context.<init>(Context.java:160)
        at net.imagej.ImageJ.<init>(ImageJ.java:77)
        at net.imagej.Main.main(Main.java:54)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:291)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:198)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:89)
Caused by: javassist.CannotCompileException: No code replaced!
        at net.imagej.patcher.CodeHacker$EagerExprEditor.instrument(CodeHacker.java:1290)
        at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:720)
        ... 33 more
java.lang.IllegalArgumentException: Cannot handle replace call to openImage in ij.plugin.FolderOpener's public void run(java.lang.String arg)
        at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:723)
        at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:648)
        at net.imagej.patcher.LegacyExtensions.installOpenInterceptor(LegacyExtensions.java:764)
        at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:294)
        at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:306)
        at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:107)
        at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:100)
        at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:494)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:395)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:374)
        at net.imagej.legacy.LegacyService.<clinit>(LegacyService.java:141)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:300)
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:267)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:229)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:192)
        at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:164)
        at org.scijava.Context.<init>(Context.java:278)
        at org.scijava.Context.<init>(Context.java:234)
        at org.scijava.Context.<init>(Context.java:174)
        at org.scijava.Context.<init>(Context.java:160)
        at net.imagej.ImageJ.<init>(ImageJ.java:77)
        at net.imagej.Main.main(Main.java:54)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:291)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:198)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:89)
Caused by: javassist.CannotCompileException: No code replaced!
        at net.imagej.patcher.CodeHacker$EagerExprEditor.instrument(CodeHacker.java:1290)
        at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:720)
        ... 33 more
[DEBUG] Creating service: net.imagej.display.DefaultOverlayService
[DEBUG] Creating service: net.imagej.ui.awt.AWTRenderingService
[DEBUG] Created service 'net.imagej.ui.awt.AWTRenderingService' in 0 ms
[DEBUG] Created service 'net.imagej.display.DefaultOverlayService' in 4 ms
[DEBUG] Creating service: net.imagej.threshold.DefaultThresholdService
[DEBUG] Created service 'net.imagej.threshold.DefaultThresholdService' in 1 ms
...
[DEBUG] publish(
        context = org.scijava.Context@4ae33a11
        consumed = false,null,null), called from non-EDT Thread:null
[DEBUG] Received command line arguments:
[DEBUG] Discovered user interface: net.imagej.legacy.ui.LegacyUI
[DEBUG] Discovered user interface: org.scijava.ui.swing.sdi.SwingSDIUI
[DEBUG] Discovered user interface: org.scijava.ui.awt.AWTUI
[DEBUG] Discovered user interface: org.scijava.ui.swing.mdi.SwingMdiUI
[DEBUG] Discovered user interface: org.scijava.ui.headless.HeadlessUI
[DEBUG] Launching user interface: net.imagej.legacy.ui.LegacyUI
[DEBUG] Found 18 ConsoleArgument plugins.
[DEBUG] Found 7 IOPlugin plugins.
[DEBUG] Found 3 LocationResolver plugins.
[DEBUG] Found 23 OptionsPlugin plugins.
[DEBUG] Found 139 Converter plugins.
[DEBUG] Found 5 CodeRunner plugins.
[DEBUG] Found 1 ScriptHeader plugins.
[DEBUG] Found 10 SearchActionFactory plugins.
[DEBUG] Found 2 TextFormat plugins.
[DEBUG] Found 26 Tool plugins.
[DEBUG] Found 4 DragAndDropHandler plugins.
[DEBUG] Found 3 LanguageSupportPlugin plugins.
[DEBUG] Found 2 BatchInputProvider plugins.
[DEBUG] Found 16 Codec plugins.
[DEBUG] Found 3 PlaneConverter plugins.
[DEBUG] Found 25 Translator plugins.
[DEBUG] Found 17 ThresholdMethod plugins.
[DEBUG] Found 2 AutoscaleMethod plugins.
[DEBUG] Found 13 CalculatorOp plugins.
[DEBUG] publish(
        context = org.scijava.Context@4ae33a11
        consumed = false
        ui = legacy,null,null), called from non-EDT Thread:null
```

**Comment by mkitti** [comment]
On Windows or Linux, creating a ImageJ.cfg that contains this seems to make FIJI work with a Java 8 built ImageJ1.

```
# ImageJ startup properties
jvmargs = -Xverify:none
```

I imagine a `Contents/Info.plist` with this would work on macOS:
```
	<key>fiji</key>
	<dict>
		<key>memory</key>
		<string>auto</string>
		<key>system</key>
		<string>0</string>
		<key>allowMultiple</key>
		<string>false</string>
		<key>JVMOptions</key>
		<string>-Xverify:none</string>
		<key>DefaultArguments</key>
		<string></string>
	</dict>
```

Is there a way to make this a default option via imagej-launcher?

**Comment by ctrueden** [comment]
Using `-Xverify:none` is a great trick to get up and running. But please be aware it is a hack. ImageJ will not be patched fully successfully by ij1-patcher in that case, and there will be problems with the related behavior as a consequence.

The right fix is to update ij1-patcher to understand changes made to ImageJ in 1.53g and later. @mkitti and I started working on that together; work so far exists on the `update-for-153p` branch.

One ij1-patcher supports all versions of ImageJ up through the latest (currently 1.53p), we can declare this issue fixed.

**Comment by mkitti** [comment]
See https://github.com/imagej/ij1-patcher/pull/52

**Comment by ctrueden** [comment]
The ij1-patcher now supports ImageJ up to 1.53p, thanks to @mkitti.
